// <auto-generated />
namespace HospitalProjectTeam4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class zameer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zameer));
        
        string IMigrationMetadata.Id
        {
            get { return "202004102340482_zameer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
