// <auto-generated />
namespace HospitalProjectTeam4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class checkin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkin));
        
        string IMigrationMetadata.Id
        {
            get { return "202004140842563_check-in"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
